#######################################
#            Makefile Caml            #
#                                     #
#                                     #
#                                     #
#                                     #
#                                     #
#######################################
all: test1

test1:
	ocamlbuild test1.native

test2:
	ocamlbuild test2.native

clean:
	rm -rf _build/ test1.native test2.native test3.native
